server:
  port: 8082

logging:
  level:
    root: info

spring:
  aop:
    proxy-target-class: true
    auto: true
  application:
    name: YuyueAdmin
  profiles:
    active: ${PROFILE:dev}
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 10000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: select 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true


mybatis-plus:
  type-aliases-package: com.yuyue.admin.dal.po
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  #type-enums-package: com.whats.common.constant
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
