logging:
  level:
    com.whats.admin: debug

spring:
  datasource:
    url: jdbc:mysql://ec2-54-212-130-14.us-west-2.compute.amazonaws.com:3306/unbiased?characterEncoding=UTF-8
    username: root
    password: Unbiased@17888
